-- ============================================================
-- costumes：新增全部服裝資料（資料來源：browndust2-db.souseha.com）
--
-- 目的：將服裝資料庫（管理後台「服裝設定」）初始化為完整清單，
--       涵蓋角色所有服裝（含中文/英文名稱、角色、圖片、排序）。
--
-- 資料來源：https://browndust2-db.souseha.com 的服裝資料集
--           （characters_base + costumes_i18n）
-- 圖片來源：https://image-bd2db.souseha.com/characters/{costumeId}.webp
--
-- 欄位對應：
--   id            = 服裝 id（costumeId，如 Lathel_1）
--   name          = 中文名（costumeName）
--   name_e        = 英文名（costumeName_en）
--   character_id  = 所屬角色 id（characterId，對應 characters.id）
--   image_name    = 圖片 basename（= costumeId，前端會自動補 .webp）
--   order_num     = 排序（costumeCode 數字）
--   is_new        = 是否新服裝（資料集無明確標記，先行設為 false，
--                   可由管理後台手動勾選）
--
-- 執行方式：請先執行 seed_characters_from_bd2db.sql（建立角色的外鍵參照），
--           再執行本檔。
-- 設計：使用 ON CONFLICT (id) DO NOTHING，可安全重複執行。
-- ============================================================

INSERT INTO costumes (id, name, name_e, character_id, image_name, order_num, is_new) VALUES
  ('Alec_1', '毀滅之星', 'The Destruction', 'Alec', 'Alec_1', 1, false),
  ('Alec_2', '劍之毀滅者', 'Sword Breaker', 'Alec', 'Alec_2', 2, false),
  ('Anastasia_1', '和藹的女僕', 'Gentle Maid', 'Anastasia', 'Anastasia_1', 1, false),
  ('Anastasia_2', '火之塗鴉', 'Fire Graffiti', 'Anastasia', 'Anastasia_2', 2, false),
  ('Andrew_1', '忠誠耿直的管家', 'Loyal Butler', 'Andrew', 'Andrew_1', 1, false),
  ('Andrew_2', '專家', 'Specialist', 'Andrew', 'Andrew_2', 2, false),
  ('Angelica_1', '墮落之星', 'The Fallen', 'Angelica', 'Angelica_1', 1, false),
  ('Angelica_2', '泳池派對', 'Pool Party', 'Angelica', 'Angelica_2', 2, false),
  ('Angelica_3', '霓虹救星', 'Neon Savior', 'Angelica', 'Angelica_3', 3, false),
  ('Aquila_1', '戰場猛獸', 'Savage Warrior', 'Aquila', 'Aquila_1', 1, false),
  ('Arines_1', '活力的祭司', 'Priest of Vitality', 'Arines', 'Arines_1', 1, false),
  ('Beatrice_1', '部族的大戰士', 'Mighty Warrior of the Tribe', 'Beatrice', 'Beatrice_1', 1, false),
  ('Bernie_1', '義賊少女', 'Righteous Raider Girl', 'Bernie', 'Bernie_1', 1, false),
  ('Blade_1', '使者', 'Apostle', 'Blade', 'Blade_1', 1, false),
  ('Blade_2', '小公主', 'Young Lady', 'Blade', 'Blade_2', 2, false),
  ('Blade_3', '溫泉劍客', 'Onsen Swordfighter', 'Blade', 'Blade_3', 3, false),
  ('Carlson_1', '傭兵騎士', 'Mercenary Knight', 'Carlson', 'Carlson_1', 1, false),
  ('Celia_1', '詛咒之星', 'The Curse', 'Celia', 'Celia_1', 1, false),
  ('Celia_2', '大魔女的後裔', 'Descendant of the Great Witch', 'Celia', 'Celia_2', 2, false),
  ('Celia_3', '化裝舞會兔女郎', 'Masquerade Bunny', 'Celia', 'Celia_3', 3, false),
  ('Cynthia_1', '酷寒中的熱氣', 'Warmth Within the Severe Cold', 'Cynthia', 'Cynthia_1', 1, false),
  ('Dalvi_1', '明月', 'Bright Moon', 'Dalvi', 'Dalvi_1', 1, false),
  ('Dalvi_2', '暑假', 'Summer Vacation', 'Dalvi', 'Dalvi_2', 2, false),
  ('Dalvi_3', '詭計戀人', 'Tricky Lover', 'Dalvi', 'Dalvi_3', 3, false),
  ('Darian_1', '啟示之夢', 'Prophetic Dream', 'Darian', 'Darian_1', 1, false),
  ('Darian_2', '苦甜兔女郎', 'Bittersweet Bunny', 'Darian', 'Darian_2', 2, false),
  ('Diana_1', '未知的探究者', 'Adventurer of the Unknown', 'Diana', 'Diana_1', 1, false),
  ('Diana_2', '反烏托邦', 'Anti-Dystopia', 'Diana', 'Diana_2', 2, false),
  ('Diana_3', '魔法革新者', 'Magical Innovator', 'Diana', 'Diana_3', 3, false),
  ('Eclipse_1', '空間魔女', 'The Dimension Witch', 'Eclipse', 'Eclipse_1', 1, false),
  ('Eclipse_2', '惡夢兔女郎', 'Nightmare Bunny', 'Eclipse', 'Eclipse_2', 2, false),
  ('Eclipse_3', '海邊度假', 'Beach Vacation', 'Eclipse', 'Eclipse_3', 3, false),
  ('Eclipse_4', '夢中的新娘', 'Dream Bride', 'Eclipse', 'Eclipse_4', 4, false),
  ('Eleaneer_1', '貫穿的魔弓', 'Piercing Magic Bow', 'Eleaneer', 'Eleaneer_1', 1, false),
  ('Eleaneer_2', 'B級偶像', 'B-Rank Idol', 'Eleaneer', 'Eleaneer_2', 2, false),
  ('Eleaneer_3', '酷魅兔女郎', 'Shadow Bunny', 'Eleaneer', 'Eleaneer_3', 3, false),
  ('Elise_1', '可愛的小姐', 'Lovely Lady', 'Elise', 'Elise_1', 1, false),
  ('Elise_2', '代號O', 'Code Name O', 'Elise', 'Elise_2', 2, false),
  ('Elise_3', '天真的小姐', 'Naive Lady', 'Elise', 'Elise_3', 3, false),
  ('Elpis_1', '救贖之手', 'Hand of Salvation', 'Elpis', 'Elpis_1', 1, false),
  ('Emma_1', '難伺候的問題學生', 'Haggard Delinquent', 'Emma', 'Emma_1', 1, false),
  ('Emma_2', '學校女王', 'School Queen', 'Emma', 'Emma_2', 2, false),
  ('Eris_1', '受祝福的冒險家', 'Esteemed Adventurer', 'Eris', 'Eris_1', 1, false),
  ('Eris_2', '只屬於你的貓咪', 'Your Very Own Cat', 'Eris', 'Eris_2', 2, false),
  ('Fred_1', '盧戈守衛隊', 'Lugo Defense Force', 'Fred', 'Fred_1', 1, false),
  ('Glacia_1', '愛麗絲', 'Alice', 'Glacia', 'Glacia_1', 1, false),
  ('Glacia_2', '糾察隊', 'Disciplinary Committee', 'Glacia', 'Glacia_2', 2, false),
  ('Glacia_3', '天守繼承者', 'Heavenly Guardian Successor', 'Glacia', 'Glacia_3', 3, false),
  ('GoblinSlayer_1', '小鬼殺手', 'Orcbolg', 'GoblinSlayer', 'GoblinSlayer_1', 1, false),
  ('Granadair_1', '葛洛堤女王', 'Queen of Gluttis', 'Granadair', 'Granadair_1', 1, false),
  ('Granadair_2', '淨化巫女', 'Shrine Maiden of Purification', 'Granadair', 'Granadair_2', 2, false),
  ('Granhildr_1', '虛無之星', 'The Void', 'Granhildr', 'Granhildr_1', 1, false),
  ('Granhildr_2', '回歸偶像', 'Comeback Idol', 'Granhildr', 'Granhildr_2', 2, false),
  ('Granhildr_3', '惡作劇幽靈', 'Boo Ghost', 'Granhildr', 'Granhildr_3', 3, false),
  ('Granhildr_4', '戰地醫護兵', 'Combat Medic', 'Granhildr', 'Granhildr_4', 4, false),
  ('Gray_1', '迷霧神射手', 'Sharpshooter of the Mist', 'Gray', 'Gray_1', 1, false),
  ('Gray_2', 'B級老闆', 'B-Rank Manager', 'Gray', 'Gray_2', 2, false),
  ('Gray_3', '先鋒大將', 'Vanguard', 'Gray', 'Gray_3', 3, false),
  ('Gray_4', '泳池派對', 'Pool Party', 'Gray', 'Gray_4', 4, false),
  ('Gynt_1', '盧戈獵人', 'Lugo Hunter', 'Gynt', 'Gynt_1', 1, false),
  ('Helena_1', '頂尖偶像', 'Top Idol', 'Helena', 'Helena_1', 1, false),
  ('Helena_2', 'B級偶像', 'B-Rank Idol', 'Helena', 'Helena_2', 2, false),
  ('Helena_3', '客棧的陽光', 'Sunny Inn Hand', 'Helena', 'Helena_3', 3, false),
  ('HighElfArcher_1', '星風之女', 'Daughter of Starwind', 'HighElfArcher', 'HighElfArcher_1', 1, false),
  ('Hikage_1', '和藹的無情', 'Kind Ruthlessness', 'Hikage', 'Hikage_1', 1, false),
  ('Ikaruga_1', '清廉之焰', 'Noble Flame', 'Ikaruga', 'Ikaruga_1', 1, false),
  ('Ingrid_1', '卡迪斯的子彈', 'Kardis'' Bullet', 'Ingrid', 'Ingrid_1', 1, false),
  ('Jayden_1', '美少女信奉者', 'Beautiful Girl Devotee', 'Jayden', 'Jayden_1', 1, false),
  ('Jayden_2', '漫畫研究社', 'Manga Research Club', 'Jayden', 'Jayden_2', 2, false),
  ('Julie_1', '恢復師', 'Healer', 'Julie', 'Julie_1', 1, false),
  ('Justia_1', '皎潔死神', 'White Reaper', 'Justia', 'Justia_1', 1, false),
  ('Justia_2', '血騎士', 'Knight of Blood', 'Justia', 'Justia_2', 2, false),
  ('Justia_3', '血之貪食者', 'Blood Glutton', 'Justia', 'Justia_3', 3, false),
  ('Justia_4', '劍道社', 'Kendo Club', 'Justia', 'Justia_4', 4, false),
  ('Justia_5', '泳池派對', 'Pool Party', 'Justia', 'Justia_5', 5, false),
  ('Kry_1', '解放的掠奪者', 'Liberated Marauder', 'Kry', 'Kry_1', 1, false),
  ('Kry_2', '克萊服裝', 'Violent Student', 'Kry', 'Kry_2', 2, false),
  ('Lathel_1', '草藥獵人', 'Herb Tracker', 'Lathel', 'Lathel_1', 1, false),
  ('Lathel_2', '孤獨的生存者', 'Lonely Survivor', 'Lathel', 'Lathel_2', 2, false),
  ('Lathel_3', '霍爾蒙克斯', 'Homunculus', 'Lathel', 'Lathel_3', 3, false),
  ('Lathel_4', '暗黑騎士', 'Dark Knight', 'Lathel', 'Lathel_4', 4, false),
  ('Lathel_5', '復仇的誓約', 'Promise of Vengeance', 'Lathel', 'Lathel_5', 5, false),
  ('Lathel_6', '泳池派對', 'Pool Party', 'Lathel', 'Lathel_6', 6, false),
  ('Layla_1', '創造的鐵砧', 'Anvil of Creation', 'Layla', 'Layla_1', 1, false),
  ('Lecliss_1', '殺人娃娃', 'Killer Doll', 'Lecliss', 'Lecliss_1', 1, false),
  ('Lecliss_2', '安卓女王', 'Android Queen', 'Lecliss', 'Lecliss_2', 2, false),
  ('Levia_1', '田徑社社長', 'Track and Field Captain', 'Levia', 'Levia_1', 1, false),
  ('Levia_2', '忌妒之夜', 'Night of Jealousy', 'Levia', 'Levia_2', 2, false),
  ('Levia_3', '過熱', 'Overheat', 'Levia', 'Levia_3', 3, false),
  ('Liatris_1', '羅戴夫之星', 'Rodev''s Star', 'Liatris', 'Liatris_1', 1, false),
  ('Liatris_2', '霓虹跟蹤狂', 'Neon Stalker', 'Liatris', 'Liatris_2', 2, false),
  ('Liatris_3', '女僕代號R', 'Maid Name R', 'Liatris', 'Liatris_3', 3, false),
  ('Liberta_1', '溫泉管理者', 'Onsen Manager', 'Liberta', 'Liberta_1', 1, false),
  ('Liberta_2', '暗黑聖女', 'Dark Saintess', 'Liberta', 'Liberta_2', 2, false),
  ('Liberta_3', '奇蹟玫瑰', 'Miracle Rose', 'Liberta', 'Liberta_3', 3, false),
  ('Lisianne_1', '流浪神職人員', 'Wandering Priest', 'Lisianne', 'Lisianne_1', 1, false),
  ('Loen_1', '最後希望', 'Last Hope', 'Loen', 'Loen_1', 1, false),
  ('Loen_2', '田徑社社員', 'Track and Field Team', 'Loen', 'Loen_2', 2, false),
  ('Loen_3', '名人兔女郎', 'Celebrity Bunny', 'Loen', 'Loen_3', 3, false),
  ('Lucrezia_1', '誘惑的翅膀', 'Seductive Wings', 'Lucrezia', 'Lucrezia_1', 1, false),
  ('Luvencia_1', '印鑑掠奪者', 'Deal Snatcher', 'Luvencia', 'Luvencia_1', 1, false),
  ('Luvencia_2', '野犬', 'Wild Dog', 'Luvencia', 'Luvencia_2', 2, false),
  ('Luvencia_3', '海洋先鋒', 'Ocean Vanguard', 'Luvencia', 'Luvencia_3', 3, false),
  ('Lydia_1', '實習槍兵', 'Apprentice Spearman', 'Lydia', 'Lydia_1', 1, false),
  ('Mamonir_1', '死亡之夜', 'Night of Death', 'Mamonir', 'Mamonir_1', 1, false),
  ('Mamonir_2', '奇蹟海洋', 'Miracle Marine', 'Mamonir', 'Mamonir_2', 2, false),
  ('Maria_1', '大魔法師', 'Archmage', 'Maria', 'Maria_1', 1, false),
  ('Michaela_1', '海邊正義', 'Beachside Justice', 'Michaela', 'Michaela_1', 1, false),
  ('Michaela_2', '簽名女王', 'Queen of Signatures', 'Michaela', 'Michaela_2', 2, false),
  ('Michaela_3', '神聖者', 'Acting Archbishop', 'Michaela', 'Michaela_3', 3, false),
  ('Morpeah_1', '海邊度假', 'Beach Vacation', 'Morpeah', 'Morpeah_1', 1, false),
  ('Morpeah_2', '白日夢兔女郎', 'Daydream Bunny', 'Morpeah', 'Morpeah_2', 2, false),
  ('Morpeah_3', '使者', 'Apostle', 'Morpeah', 'Morpeah_3', 3, false),
  ('Nartas_1', '無名道士', 'Anonymous Sage', 'Nartas', 'Nartas_1', 1, false),
  ('Nebris_1', '鬆散的救生員', 'Laid-back Lifeguard', 'Nebris', 'Nebris_1', 1, false),
  ('Nebris_2', '迷宮的門衛', 'Labyrinth Gatekeeper', 'Nebris', 'Nebris_2', 2, false),
  ('Nebris_3', '新進員工', 'New Hire', 'Nebris', 'Nebris_3', 3, false),
  ('Nekyndalia_1', '致命之眼', 'Deadeye', 'Nekyndalia', 'Nekyndalia_1', 1, false),
  ('Olivier_1', '墮落之翼', 'Fallen Wings', 'Olivier', 'Olivier_1', 1, false),
  ('Olivier_2', '忠實之翼', 'Faithful Wings', 'Olivier', 'Olivier_2', 2, false),
  ('Olivier_3', '使者', 'Apostle', 'Olivier', 'Olivier_3', 3, false),
  ('Olivier_4', '引退的傳奇', 'Retired Legend', 'Olivier', 'Olivier_4', 4, false),
  ('Olstein_1', '魔獸學家', 'The Fiend Scholar', 'Olstein', 'Olstein_1', 1, false),
  ('Olstein_2', '青雲道士', 'Sage of Blue Clouds', 'Olstein', 'Olstein_2', 2, false),
  ('Palette_1', '恐懼之夢', 'Shattered Dream', 'Palette', 'Palette_1', 1, false),
  ('Palette_2', '奇蹟紫羅蘭', 'Miracle Violet', 'Palette', 'Palette_2', 2, false),
  ('Priestess_1', '地母神的祭司', 'Earth Mother Believer', 'Priestess', 'Priestess_1', 1, false),
  ('Rafina_1', '鋼鐵引擎', 'Steel Engine', 'Rafina', 'Rafina_1', 1, false),
  ('Rafina_2', '代號A', 'Code Name A', 'Rafina', 'Rafina_2', 2, false),
  ('Rafina_3', '遊戲社', 'Game Club', 'Rafina', 'Rafina_3', 3, false),
  ('Refithea_1', '貪婪之星', 'The Gluttonous', 'Refithea', 'Refithea_1', 1, false),
  ('Refithea_2', '純白的祝福', 'Pure White Blessing', 'Refithea', 'Refithea_2', 2, false),
  ('Refithea_3', '水上精靈', 'Poolside Fairy', 'Refithea', 'Refithea_3', 3, false),
  ('Remnunt_1', '戰鬥醫師', 'Combat Doctor', 'Remnunt', 'Remnunt_1', 1, false),
  ('Rigenette_1', '小獵人', 'Little Hunter', 'Rigenette', 'Rigenette_1', 1, false),
  ('Rou_1', '白色貓咪', 'White Cat', 'Rou', 'Rou_1', 1, false),
  ('Rou_2', '小紅帽', 'Red Riding Hood', 'Rou', 'Rou_2', 2, false),
  ('Rou_3', '自然的腳爪', 'Nature''s Claw', 'Rou', 'Rou_3', 3, false),
  ('Rou_4', '流浪貓', 'Stray Cat', 'Rou', 'Rou_4', 4, false),
  ('Roxy_1', '受尊敬的師傅', 'Respected Master', 'Roxy', 'Roxy_1', 1, false),
  ('Roxy_2', '洩露的慾望', 'Emerging Desire', 'Roxy', 'Roxy_2', 2, false),
  ('Rubia_1', '沙漠之刺', 'Thorn of the Desert', 'Rubia', 'Rubia_1', 1, false),
  ('Rubia_2', '大海女帝', 'Empress of the Ocean', 'Rubia', 'Rubia_2', 2, false),
  ('Rubia_3', '女僕代號C', 'Maid Name C', 'Rubia', 'Rubia_3', 3, false),
  ('Rubia_4', '女僕比基尼', 'Maid Bikini', 'Rubia', 'Rubia_4', 4, false),
  ('SacredJustia_1', '找回的命運', 'Reclaimed Destiny', 'SacredJustia', 'SacredJustia_1', 1, false),
  ('Samay_1', '溫柔的解放者', 'Kind Liberator', 'Samay', 'Samay_1', 1, false),
  ('Samay_2', '和藹的學生', 'Kind Student', 'Samay', 'Samay_2', 2, false),
  ('Scheherazade_1', '蒼藍魔女', 'Lapis Witch', 'Scheherazade', 'Scheherazade_1', 1, false),
  ('Scheherazade_2', '魔法學校教授', 'Magic School Professor', 'Scheherazade', 'Scheherazade_2', 2, false),
  ('Scheherazade_3', '代號S', 'Code Name S', 'Scheherazade', 'Scheherazade_3', 3, false),
  ('Scheherazade_4', '泳池派對', 'Pool Party', 'Scheherazade', 'Scheherazade_4', 4, false),
  ('Seir_1', '惡魔之女', 'Demon''s Daughter', 'Seir', 'Seir_1', 1, false),
  ('Seir_2', 'B級偶像', 'B-Rank Idol', 'Seir', 'Seir_2', 2, false),
  ('Seir_3', '新進員工', 'New Hire', 'Seir', 'Seir_3', 3, false),
  ('Sonya_1', '潛藏的夢', 'Shadowed Dream', 'Sonya', 'Sonya_1', 1, false),
  ('Sonya_2', '賣南瓜的少女', 'Little Pumpkin Girl', 'Sonya', 'Sonya_2', 2, false),
  ('SwordMaiden_1', '至高神的大主教', 'Supreme God Archbishop', 'SwordMaiden', 'SwordMaiden_1', 1, false),
  ('Sylvia_1', '沙漠之花', 'Desert Flower', 'Sylvia', 'Sylvia_1', 1, false),
  ('Sylvia_2', '劍后', 'The Sword Queen', 'Sylvia', 'Sylvia_2', 2, false),
  ('Sylvia_3', '海軍上將', 'Admiral', 'Sylvia', 'Sylvia_3', 3, false),
  ('Sylvia_4', '比基尼特務', 'Bikini Agent', 'Sylvia', 'Sylvia_4', 4, false),
  ('Teresse_1', '破壞的天使', 'Angel of Destruction', 'Teresse', 'Teresse_1', 1, false),
  ('Teresse_2', '保健社', 'Medical Club', 'Teresse', 'Teresse_2', 2, false),
  ('Teresse_3', '海邊天使', 'Beachside Angel', 'Teresse', 'Teresse_3', 3, false),
  ('Tyr_1', '星光守護者', 'Starlight Guardian', 'Tyr', 'Tyr_1', 1, false),
  ('Tyr_2', '軟萌兔女郎', 'Innocent Bunny', 'Tyr', 'Tyr_2', 2, false),
  ('Venaka_1', 'DJ', 'DJ', 'Venaka', 'Venaka_1', 1, false),
  ('Venaka_2', '風之舞姬', 'Wind Dancer', 'Venaka', 'Venaka_2', 2, false),
  ('Ventana_1', '白雪', 'Snow White', 'Ventana', 'Ventana_1', 1, false),
  ('Ventana_2', '回歸偶像', 'Comeback Idol', 'Ventana', 'Ventana_2', 2, false),
  ('Ventana_3', '溫泉修行者', 'Onsen Practitioner', 'Ventana', 'Ventana_3', 3, false),
  ('Wiggle_1', '炸彈狂', 'Bomb Fanatic', 'Wiggle', 'Wiggle_1', 1, false),
  ('Wiggle_2', '帽T下的炸彈', 'Bomb in the Hoodie', 'Wiggle', 'Wiggle_2', 2, false),
  ('Wilhelmina_1', '鋼鐵君主', 'Iron Monarch', 'Wilhelmina', 'Wilhelmina_1', 1, false),
  ('Wilhelmina_2', '水上樂園女王', 'Water Park Queen', 'Wilhelmina', 'Wilhelmina_2', 2, false),
  ('Wilhelmina_3', '冰雪女王', 'Frozen Queen', 'Wilhelmina', 'Wilhelmina_3', 3, false),
  ('Yomi_1', '溫和的破壞者', 'Gentle Destroyer', 'Yomi', 'Yomi_1', 1, false),
  ('Yozakura_1', '信念之拳', 'Fist of Conviction', 'Yozakura', 'Yozakura_1', 1, false),
  ('Yumi_1', '雪花之舞', 'Dancing Snowflake', 'Yumi', 'Yumi_1', 1, false),
  ('Yuri_1', '白雷', 'Whitebolt', 'Yuri', 'Yuri_1', 1, false),
  ('Yuri_2', '回歸偶像', 'Comeback Idol', 'Yuri', 'Yuri_2', 2, false),
  ('Zenith_1', '羅賓漢', 'Robin Hood', 'Zenith', 'Zenith_1', 1, false),
  ('Zenith_2', '水上守護者', 'Poolside Guardian', 'Zenith', 'Zenith_2', 2, false)
ON CONFLICT (id) DO NOTHING;

-- ------------------------------------------------------------
-- 驗證：應回傳 184 列
-- ------------------------------------------------------------
SELECT count(*) AS total FROM costumes;
